# Generated by Django 5.0 on 2023-12-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_brand_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
    ]
