# Generated by Django 5.0 on 2023-12-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_product_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sufix',
            field=models.CharField(default='Generico', max_length=20),
        ),
    ]
