# Generated by Django 5.0 on 2023-12-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_brand_sufix'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sufix',
            field=models.CharField(default='as', max_length=100),
        ),
    ]
