# Generated by Django 5.0 on 2023-12-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_brand_sufix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='sufix',
        ),
    ]
