# Generated by Django 5.0 on 2023-12-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_imageproduc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProduc',
            new_name='ImageProduct',
        ),
    ]
