# Generated by Django 5.0 on 2023-12-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_imageproduc_imageproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='producto',
            new_name='product',
        ),
    ]
