# Generated by Django 5.0 on 2023-12-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_product_image_product_state_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
