# Generated by Django 5.0 on 2023-12-26 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_tags_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.TextField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='website.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
