# Generated by Django 5.0 on 2023-12-28 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_inventory_month_alter_imageproduct_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='month',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AddField(
            model_name='inventory',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='state',
            field=models.TextField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], default='1', max_length=100),
        ),
    ]
