# Generated by Django 5.0 on 2023-12-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_seller_remove_sales_month_sales_created_sales_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales',
            new_name='Sale',
        ),
    ]
