# Generated by Django 5.0 on 2024-01-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_product_sale_product_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit_seller',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
