# Generated by Django 5.0 on 2024-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_sale_profit_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='registredby',
            field=models.CharField(default='nobody', max_length=100),
        ),
    ]
