# Generated by Django 5.0 on 2024-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_sale_registredby'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
